package com.unbank.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ShixinUnitExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public ShixinUnitExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andInameIsNull() {
			addCriterion("iname is null");
			return (Criteria) this;
		}

		public Criteria andInameIsNotNull() {
			addCriterion("iname is not null");
			return (Criteria) this;
		}

		public Criteria andInameEqualTo(String value) {
			addCriterion("iname =", value, "iname");
			return (Criteria) this;
		}

		public Criteria andInameNotEqualTo(String value) {
			addCriterion("iname <>", value, "iname");
			return (Criteria) this;
		}

		public Criteria andInameGreaterThan(String value) {
			addCriterion("iname >", value, "iname");
			return (Criteria) this;
		}

		public Criteria andInameGreaterThanOrEqualTo(String value) {
			addCriterion("iname >=", value, "iname");
			return (Criteria) this;
		}

		public Criteria andInameLessThan(String value) {
			addCriterion("iname <", value, "iname");
			return (Criteria) this;
		}

		public Criteria andInameLessThanOrEqualTo(String value) {
			addCriterion("iname <=", value, "iname");
			return (Criteria) this;
		}

		public Criteria andInameLike(String value) {
			addCriterion("iname like", value, "iname");
			return (Criteria) this;
		}

		public Criteria andInameNotLike(String value) {
			addCriterion("iname not like", value, "iname");
			return (Criteria) this;
		}

		public Criteria andInameIn(List<String> values) {
			addCriterion("iname in", values, "iname");
			return (Criteria) this;
		}

		public Criteria andInameNotIn(List<String> values) {
			addCriterion("iname not in", values, "iname");
			return (Criteria) this;
		}

		public Criteria andInameBetween(String value1, String value2) {
			addCriterion("iname between", value1, value2, "iname");
			return (Criteria) this;
		}

		public Criteria andInameNotBetween(String value1, String value2) {
			addCriterion("iname not between", value1, value2, "iname");
			return (Criteria) this;
		}

		public Criteria andCasecodeIsNull() {
			addCriterion("caseCode is null");
			return (Criteria) this;
		}

		public Criteria andCasecodeIsNotNull() {
			addCriterion("caseCode is not null");
			return (Criteria) this;
		}

		public Criteria andCasecodeEqualTo(String value) {
			addCriterion("caseCode =", value, "casecode");
			return (Criteria) this;
		}

		public Criteria andCasecodeNotEqualTo(String value) {
			addCriterion("caseCode <>", value, "casecode");
			return (Criteria) this;
		}

		public Criteria andCasecodeGreaterThan(String value) {
			addCriterion("caseCode >", value, "casecode");
			return (Criteria) this;
		}

		public Criteria andCasecodeGreaterThanOrEqualTo(String value) {
			addCriterion("caseCode >=", value, "casecode");
			return (Criteria) this;
		}

		public Criteria andCasecodeLessThan(String value) {
			addCriterion("caseCode <", value, "casecode");
			return (Criteria) this;
		}

		public Criteria andCasecodeLessThanOrEqualTo(String value) {
			addCriterion("caseCode <=", value, "casecode");
			return (Criteria) this;
		}

		public Criteria andCasecodeLike(String value) {
			addCriterion("caseCode like", value, "casecode");
			return (Criteria) this;
		}

		public Criteria andCasecodeNotLike(String value) {
			addCriterion("caseCode not like", value, "casecode");
			return (Criteria) this;
		}

		public Criteria andCasecodeIn(List<String> values) {
			addCriterion("caseCode in", values, "casecode");
			return (Criteria) this;
		}

		public Criteria andCasecodeNotIn(List<String> values) {
			addCriterion("caseCode not in", values, "casecode");
			return (Criteria) this;
		}

		public Criteria andCasecodeBetween(String value1, String value2) {
			addCriterion("caseCode between", value1, value2, "casecode");
			return (Criteria) this;
		}

		public Criteria andCasecodeNotBetween(String value1, String value2) {
			addCriterion("caseCode not between", value1, value2, "casecode");
			return (Criteria) this;
		}

		public Criteria andCardnumIsNull() {
			addCriterion("cardNum is null");
			return (Criteria) this;
		}

		public Criteria andCardnumIsNotNull() {
			addCriterion("cardNum is not null");
			return (Criteria) this;
		}

		public Criteria andCardnumEqualTo(String value) {
			addCriterion("cardNum =", value, "cardnum");
			return (Criteria) this;
		}

		public Criteria andCardnumNotEqualTo(String value) {
			addCriterion("cardNum <>", value, "cardnum");
			return (Criteria) this;
		}

		public Criteria andCardnumGreaterThan(String value) {
			addCriterion("cardNum >", value, "cardnum");
			return (Criteria) this;
		}

		public Criteria andCardnumGreaterThanOrEqualTo(String value) {
			addCriterion("cardNum >=", value, "cardnum");
			return (Criteria) this;
		}

		public Criteria andCardnumLessThan(String value) {
			addCriterion("cardNum <", value, "cardnum");
			return (Criteria) this;
		}

		public Criteria andCardnumLessThanOrEqualTo(String value) {
			addCriterion("cardNum <=", value, "cardnum");
			return (Criteria) this;
		}

		public Criteria andCardnumLike(String value) {
			addCriterion("cardNum like", value, "cardnum");
			return (Criteria) this;
		}

		public Criteria andCardnumNotLike(String value) {
			addCriterion("cardNum not like", value, "cardnum");
			return (Criteria) this;
		}

		public Criteria andCardnumIn(List<String> values) {
			addCriterion("cardNum in", values, "cardnum");
			return (Criteria) this;
		}

		public Criteria andCardnumNotIn(List<String> values) {
			addCriterion("cardNum not in", values, "cardnum");
			return (Criteria) this;
		}

		public Criteria andCardnumBetween(String value1, String value2) {
			addCriterion("cardNum between", value1, value2, "cardnum");
			return (Criteria) this;
		}

		public Criteria andCardnumNotBetween(String value1, String value2) {
			addCriterion("cardNum not between", value1, value2, "cardnum");
			return (Criteria) this;
		}

		public Criteria andBusinessentityIsNull() {
			addCriterion("businessEntity is null");
			return (Criteria) this;
		}

		public Criteria andBusinessentityIsNotNull() {
			addCriterion("businessEntity is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessentityEqualTo(String value) {
			addCriterion("businessEntity =", value, "businessentity");
			return (Criteria) this;
		}

		public Criteria andBusinessentityNotEqualTo(String value) {
			addCriterion("businessEntity <>", value, "businessentity");
			return (Criteria) this;
		}

		public Criteria andBusinessentityGreaterThan(String value) {
			addCriterion("businessEntity >", value, "businessentity");
			return (Criteria) this;
		}

		public Criteria andBusinessentityGreaterThanOrEqualTo(String value) {
			addCriterion("businessEntity >=", value, "businessentity");
			return (Criteria) this;
		}

		public Criteria andBusinessentityLessThan(String value) {
			addCriterion("businessEntity <", value, "businessentity");
			return (Criteria) this;
		}

		public Criteria andBusinessentityLessThanOrEqualTo(String value) {
			addCriterion("businessEntity <=", value, "businessentity");
			return (Criteria) this;
		}

		public Criteria andBusinessentityLike(String value) {
			addCriterion("businessEntity like", value, "businessentity");
			return (Criteria) this;
		}

		public Criteria andBusinessentityNotLike(String value) {
			addCriterion("businessEntity not like", value, "businessentity");
			return (Criteria) this;
		}

		public Criteria andBusinessentityIn(List<String> values) {
			addCriterion("businessEntity in", values, "businessentity");
			return (Criteria) this;
		}

		public Criteria andBusinessentityNotIn(List<String> values) {
			addCriterion("businessEntity not in", values, "businessentity");
			return (Criteria) this;
		}

		public Criteria andBusinessentityBetween(String value1, String value2) {
			addCriterion("businessEntity between", value1, value2,
					"businessentity");
			return (Criteria) this;
		}

		public Criteria andBusinessentityNotBetween(String value1, String value2) {
			addCriterion("businessEntity not between", value1, value2,
					"businessentity");
			return (Criteria) this;
		}

		public Criteria andCourtnameIsNull() {
			addCriterion("courtName is null");
			return (Criteria) this;
		}

		public Criteria andCourtnameIsNotNull() {
			addCriterion("courtName is not null");
			return (Criteria) this;
		}

		public Criteria andCourtnameEqualTo(String value) {
			addCriterion("courtName =", value, "courtname");
			return (Criteria) this;
		}

		public Criteria andCourtnameNotEqualTo(String value) {
			addCriterion("courtName <>", value, "courtname");
			return (Criteria) this;
		}

		public Criteria andCourtnameGreaterThan(String value) {
			addCriterion("courtName >", value, "courtname");
			return (Criteria) this;
		}

		public Criteria andCourtnameGreaterThanOrEqualTo(String value) {
			addCriterion("courtName >=", value, "courtname");
			return (Criteria) this;
		}

		public Criteria andCourtnameLessThan(String value) {
			addCriterion("courtName <", value, "courtname");
			return (Criteria) this;
		}

		public Criteria andCourtnameLessThanOrEqualTo(String value) {
			addCriterion("courtName <=", value, "courtname");
			return (Criteria) this;
		}

		public Criteria andCourtnameLike(String value) {
			addCriterion("courtName like", value, "courtname");
			return (Criteria) this;
		}

		public Criteria andCourtnameNotLike(String value) {
			addCriterion("courtName not like", value, "courtname");
			return (Criteria) this;
		}

		public Criteria andCourtnameIn(List<String> values) {
			addCriterion("courtName in", values, "courtname");
			return (Criteria) this;
		}

		public Criteria andCourtnameNotIn(List<String> values) {
			addCriterion("courtName not in", values, "courtname");
			return (Criteria) this;
		}

		public Criteria andCourtnameBetween(String value1, String value2) {
			addCriterion("courtName between", value1, value2, "courtname");
			return (Criteria) this;
		}

		public Criteria andCourtnameNotBetween(String value1, String value2) {
			addCriterion("courtName not between", value1, value2, "courtname");
			return (Criteria) this;
		}

		public Criteria andAreanameIsNull() {
			addCriterion("areaName is null");
			return (Criteria) this;
		}

		public Criteria andAreanameIsNotNull() {
			addCriterion("areaName is not null");
			return (Criteria) this;
		}

		public Criteria andAreanameEqualTo(String value) {
			addCriterion("areaName =", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameNotEqualTo(String value) {
			addCriterion("areaName <>", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameGreaterThan(String value) {
			addCriterion("areaName >", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameGreaterThanOrEqualTo(String value) {
			addCriterion("areaName >=", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameLessThan(String value) {
			addCriterion("areaName <", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameLessThanOrEqualTo(String value) {
			addCriterion("areaName <=", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameLike(String value) {
			addCriterion("areaName like", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameNotLike(String value) {
			addCriterion("areaName not like", value, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameIn(List<String> values) {
			addCriterion("areaName in", values, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameNotIn(List<String> values) {
			addCriterion("areaName not in", values, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameBetween(String value1, String value2) {
			addCriterion("areaName between", value1, value2, "areaname");
			return (Criteria) this;
		}

		public Criteria andAreanameNotBetween(String value1, String value2) {
			addCriterion("areaName not between", value1, value2, "areaname");
			return (Criteria) this;
		}

		public Criteria andPartytypenameIsNull() {
			addCriterion("partyTypeName is null");
			return (Criteria) this;
		}

		public Criteria andPartytypenameIsNotNull() {
			addCriterion("partyTypeName is not null");
			return (Criteria) this;
		}

		public Criteria andPartytypenameEqualTo(String value) {
			addCriterion("partyTypeName =", value, "partytypename");
			return (Criteria) this;
		}

		public Criteria andPartytypenameNotEqualTo(String value) {
			addCriterion("partyTypeName <>", value, "partytypename");
			return (Criteria) this;
		}

		public Criteria andPartytypenameGreaterThan(String value) {
			addCriterion("partyTypeName >", value, "partytypename");
			return (Criteria) this;
		}

		public Criteria andPartytypenameGreaterThanOrEqualTo(String value) {
			addCriterion("partyTypeName >=", value, "partytypename");
			return (Criteria) this;
		}

		public Criteria andPartytypenameLessThan(String value) {
			addCriterion("partyTypeName <", value, "partytypename");
			return (Criteria) this;
		}

		public Criteria andPartytypenameLessThanOrEqualTo(String value) {
			addCriterion("partyTypeName <=", value, "partytypename");
			return (Criteria) this;
		}

		public Criteria andPartytypenameLike(String value) {
			addCriterion("partyTypeName like", value, "partytypename");
			return (Criteria) this;
		}

		public Criteria andPartytypenameNotLike(String value) {
			addCriterion("partyTypeName not like", value, "partytypename");
			return (Criteria) this;
		}

		public Criteria andPartytypenameIn(List<String> values) {
			addCriterion("partyTypeName in", values, "partytypename");
			return (Criteria) this;
		}

		public Criteria andPartytypenameNotIn(List<String> values) {
			addCriterion("partyTypeName not in", values, "partytypename");
			return (Criteria) this;
		}

		public Criteria andPartytypenameBetween(String value1, String value2) {
			addCriterion("partyTypeName between", value1, value2,
					"partytypename");
			return (Criteria) this;
		}

		public Criteria andPartytypenameNotBetween(String value1, String value2) {
			addCriterion("partyTypeName not between", value1, value2,
					"partytypename");
			return (Criteria) this;
		}

		public Criteria andGistidIsNull() {
			addCriterion("gistId is null");
			return (Criteria) this;
		}

		public Criteria andGistidIsNotNull() {
			addCriterion("gistId is not null");
			return (Criteria) this;
		}

		public Criteria andGistidEqualTo(String value) {
			addCriterion("gistId =", value, "gistid");
			return (Criteria) this;
		}

		public Criteria andGistidNotEqualTo(String value) {
			addCriterion("gistId <>", value, "gistid");
			return (Criteria) this;
		}

		public Criteria andGistidGreaterThan(String value) {
			addCriterion("gistId >", value, "gistid");
			return (Criteria) this;
		}

		public Criteria andGistidGreaterThanOrEqualTo(String value) {
			addCriterion("gistId >=", value, "gistid");
			return (Criteria) this;
		}

		public Criteria andGistidLessThan(String value) {
			addCriterion("gistId <", value, "gistid");
			return (Criteria) this;
		}

		public Criteria andGistidLessThanOrEqualTo(String value) {
			addCriterion("gistId <=", value, "gistid");
			return (Criteria) this;
		}

		public Criteria andGistidLike(String value) {
			addCriterion("gistId like", value, "gistid");
			return (Criteria) this;
		}

		public Criteria andGistidNotLike(String value) {
			addCriterion("gistId not like", value, "gistid");
			return (Criteria) this;
		}

		public Criteria andGistidIn(List<String> values) {
			addCriterion("gistId in", values, "gistid");
			return (Criteria) this;
		}

		public Criteria andGistidNotIn(List<String> values) {
			addCriterion("gistId not in", values, "gistid");
			return (Criteria) this;
		}

		public Criteria andGistidBetween(String value1, String value2) {
			addCriterion("gistId between", value1, value2, "gistid");
			return (Criteria) this;
		}

		public Criteria andGistidNotBetween(String value1, String value2) {
			addCriterion("gistId not between", value1, value2, "gistid");
			return (Criteria) this;
		}

		public Criteria andRegdateIsNull() {
			addCriterion("regDate is null");
			return (Criteria) this;
		}

		public Criteria andRegdateIsNotNull() {
			addCriterion("regDate is not null");
			return (Criteria) this;
		}

		public Criteria andRegdateEqualTo(String value) {
			addCriterion("regDate =", value, "regdate");
			return (Criteria) this;
		}

		public Criteria andRegdateNotEqualTo(String value) {
			addCriterion("regDate <>", value, "regdate");
			return (Criteria) this;
		}

		public Criteria andRegdateGreaterThan(String value) {
			addCriterion("regDate >", value, "regdate");
			return (Criteria) this;
		}

		public Criteria andRegdateGreaterThanOrEqualTo(String value) {
			addCriterion("regDate >=", value, "regdate");
			return (Criteria) this;
		}

		public Criteria andRegdateLessThan(String value) {
			addCriterion("regDate <", value, "regdate");
			return (Criteria) this;
		}

		public Criteria andRegdateLessThanOrEqualTo(String value) {
			addCriterion("regDate <=", value, "regdate");
			return (Criteria) this;
		}

		public Criteria andRegdateLike(String value) {
			addCriterion("regDate like", value, "regdate");
			return (Criteria) this;
		}

		public Criteria andRegdateNotLike(String value) {
			addCriterion("regDate not like", value, "regdate");
			return (Criteria) this;
		}

		public Criteria andRegdateIn(List<String> values) {
			addCriterion("regDate in", values, "regdate");
			return (Criteria) this;
		}

		public Criteria andRegdateNotIn(List<String> values) {
			addCriterion("regDate not in", values, "regdate");
			return (Criteria) this;
		}

		public Criteria andRegdateBetween(String value1, String value2) {
			addCriterion("regDate between", value1, value2, "regdate");
			return (Criteria) this;
		}

		public Criteria andRegdateNotBetween(String value1, String value2) {
			addCriterion("regDate not between", value1, value2, "regdate");
			return (Criteria) this;
		}

		public Criteria andGistunitIsNull() {
			addCriterion("gistUnit is null");
			return (Criteria) this;
		}

		public Criteria andGistunitIsNotNull() {
			addCriterion("gistUnit is not null");
			return (Criteria) this;
		}

		public Criteria andGistunitEqualTo(String value) {
			addCriterion("gistUnit =", value, "gistunit");
			return (Criteria) this;
		}

		public Criteria andGistunitNotEqualTo(String value) {
			addCriterion("gistUnit <>", value, "gistunit");
			return (Criteria) this;
		}

		public Criteria andGistunitGreaterThan(String value) {
			addCriterion("gistUnit >", value, "gistunit");
			return (Criteria) this;
		}

		public Criteria andGistunitGreaterThanOrEqualTo(String value) {
			addCriterion("gistUnit >=", value, "gistunit");
			return (Criteria) this;
		}

		public Criteria andGistunitLessThan(String value) {
			addCriterion("gistUnit <", value, "gistunit");
			return (Criteria) this;
		}

		public Criteria andGistunitLessThanOrEqualTo(String value) {
			addCriterion("gistUnit <=", value, "gistunit");
			return (Criteria) this;
		}

		public Criteria andGistunitLike(String value) {
			addCriterion("gistUnit like", value, "gistunit");
			return (Criteria) this;
		}

		public Criteria andGistunitNotLike(String value) {
			addCriterion("gistUnit not like", value, "gistunit");
			return (Criteria) this;
		}

		public Criteria andGistunitIn(List<String> values) {
			addCriterion("gistUnit in", values, "gistunit");
			return (Criteria) this;
		}

		public Criteria andGistunitNotIn(List<String> values) {
			addCriterion("gistUnit not in", values, "gistunit");
			return (Criteria) this;
		}

		public Criteria andGistunitBetween(String value1, String value2) {
			addCriterion("gistUnit between", value1, value2, "gistunit");
			return (Criteria) this;
		}

		public Criteria andGistunitNotBetween(String value1, String value2) {
			addCriterion("gistUnit not between", value1, value2, "gistunit");
			return (Criteria) this;
		}

		public Criteria andPerformanceIsNull() {
			addCriterion("performance is null");
			return (Criteria) this;
		}

		public Criteria andPerformanceIsNotNull() {
			addCriterion("performance is not null");
			return (Criteria) this;
		}

		public Criteria andPerformanceEqualTo(String value) {
			addCriterion("performance =", value, "performance");
			return (Criteria) this;
		}

		public Criteria andPerformanceNotEqualTo(String value) {
			addCriterion("performance <>", value, "performance");
			return (Criteria) this;
		}

		public Criteria andPerformanceGreaterThan(String value) {
			addCriterion("performance >", value, "performance");
			return (Criteria) this;
		}

		public Criteria andPerformanceGreaterThanOrEqualTo(String value) {
			addCriterion("performance >=", value, "performance");
			return (Criteria) this;
		}

		public Criteria andPerformanceLessThan(String value) {
			addCriterion("performance <", value, "performance");
			return (Criteria) this;
		}

		public Criteria andPerformanceLessThanOrEqualTo(String value) {
			addCriterion("performance <=", value, "performance");
			return (Criteria) this;
		}

		public Criteria andPerformanceLike(String value) {
			addCriterion("performance like", value, "performance");
			return (Criteria) this;
		}

		public Criteria andPerformanceNotLike(String value) {
			addCriterion("performance not like", value, "performance");
			return (Criteria) this;
		}

		public Criteria andPerformanceIn(List<String> values) {
			addCriterion("performance in", values, "performance");
			return (Criteria) this;
		}

		public Criteria andPerformanceNotIn(List<String> values) {
			addCriterion("performance not in", values, "performance");
			return (Criteria) this;
		}

		public Criteria andPerformanceBetween(String value1, String value2) {
			addCriterion("performance between", value1, value2, "performance");
			return (Criteria) this;
		}

		public Criteria andPerformanceNotBetween(String value1, String value2) {
			addCriterion("performance not between", value1, value2,
					"performance");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameIsNull() {
			addCriterion("disruptTypeName is null");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameIsNotNull() {
			addCriterion("disruptTypeName is not null");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameEqualTo(String value) {
			addCriterion("disruptTypeName =", value, "disrupttypename");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameNotEqualTo(String value) {
			addCriterion("disruptTypeName <>", value, "disrupttypename");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameGreaterThan(String value) {
			addCriterion("disruptTypeName >", value, "disrupttypename");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameGreaterThanOrEqualTo(String value) {
			addCriterion("disruptTypeName >=", value, "disrupttypename");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameLessThan(String value) {
			addCriterion("disruptTypeName <", value, "disrupttypename");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameLessThanOrEqualTo(String value) {
			addCriterion("disruptTypeName <=", value, "disrupttypename");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameLike(String value) {
			addCriterion("disruptTypeName like", value, "disrupttypename");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameNotLike(String value) {
			addCriterion("disruptTypeName not like", value, "disrupttypename");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameIn(List<String> values) {
			addCriterion("disruptTypeName in", values, "disrupttypename");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameNotIn(List<String> values) {
			addCriterion("disruptTypeName not in", values, "disrupttypename");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameBetween(String value1, String value2) {
			addCriterion("disruptTypeName between", value1, value2,
					"disrupttypename");
			return (Criteria) this;
		}

		public Criteria andDisrupttypenameNotBetween(String value1,
				String value2) {
			addCriterion("disruptTypeName not between", value1, value2,
					"disrupttypename");
			return (Criteria) this;
		}

		public Criteria andPublishdateIsNull() {
			addCriterion("publishDate is null");
			return (Criteria) this;
		}

		public Criteria andPublishdateIsNotNull() {
			addCriterion("publishDate is not null");
			return (Criteria) this;
		}

		public Criteria andPublishdateEqualTo(String value) {
			addCriterion("publishDate =", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateNotEqualTo(String value) {
			addCriterion("publishDate <>", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateGreaterThan(String value) {
			addCriterion("publishDate >", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateGreaterThanOrEqualTo(String value) {
			addCriterion("publishDate >=", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateLessThan(String value) {
			addCriterion("publishDate <", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateLessThanOrEqualTo(String value) {
			addCriterion("publishDate <=", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateLike(String value) {
			addCriterion("publishDate like", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateNotLike(String value) {
			addCriterion("publishDate not like", value, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateIn(List<String> values) {
			addCriterion("publishDate in", values, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateNotIn(List<String> values) {
			addCriterion("publishDate not in", values, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateBetween(String value1, String value2) {
			addCriterion("publishDate between", value1, value2, "publishdate");
			return (Criteria) this;
		}

		public Criteria andPublishdateNotBetween(String value1, String value2) {
			addCriterion("publishDate not between", value1, value2,
					"publishdate");
			return (Criteria) this;
		}

		public Criteria andSouceidIsNull() {
			addCriterion("souceid is null");
			return (Criteria) this;
		}

		public Criteria andSouceidIsNotNull() {
			addCriterion("souceid is not null");
			return (Criteria) this;
		}

		public Criteria andSouceidEqualTo(String value) {
			addCriterion("souceid =", value, "souceid");
			return (Criteria) this;
		}

		public Criteria andSouceidNotEqualTo(String value) {
			addCriterion("souceid <>", value, "souceid");
			return (Criteria) this;
		}

		public Criteria andSouceidGreaterThan(String value) {
			addCriterion("souceid >", value, "souceid");
			return (Criteria) this;
		}

		public Criteria andSouceidGreaterThanOrEqualTo(String value) {
			addCriterion("souceid >=", value, "souceid");
			return (Criteria) this;
		}

		public Criteria andSouceidLessThan(String value) {
			addCriterion("souceid <", value, "souceid");
			return (Criteria) this;
		}

		public Criteria andSouceidLessThanOrEqualTo(String value) {
			addCriterion("souceid <=", value, "souceid");
			return (Criteria) this;
		}

		public Criteria andSouceidLike(String value) {
			addCriterion("souceid like", value, "souceid");
			return (Criteria) this;
		}

		public Criteria andSouceidNotLike(String value) {
			addCriterion("souceid not like", value, "souceid");
			return (Criteria) this;
		}

		public Criteria andSouceidIn(List<String> values) {
			addCriterion("souceid in", values, "souceid");
			return (Criteria) this;
		}

		public Criteria andSouceidNotIn(List<String> values) {
			addCriterion("souceid not in", values, "souceid");
			return (Criteria) this;
		}

		public Criteria andSouceidBetween(String value1, String value2) {
			addCriterion("souceid between", value1, value2, "souceid");
			return (Criteria) this;
		}

		public Criteria andSouceidNotBetween(String value1, String value2) {
			addCriterion("souceid not between", value1, value2, "souceid");
			return (Criteria) this;
		}

		public Criteria andClawertimeIsNull() {
			addCriterion("clawerTime is null");
			return (Criteria) this;
		}

		public Criteria andClawertimeIsNotNull() {
			addCriterion("clawerTime is not null");
			return (Criteria) this;
		}

		public Criteria andClawertimeEqualTo(Date value) {
			addCriterionForJDBCDate("clawerTime =", value, "clawertime");
			return (Criteria) this;
		}

		public Criteria andClawertimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("clawerTime <>", value, "clawertime");
			return (Criteria) this;
		}

		public Criteria andClawertimeGreaterThan(Date value) {
			addCriterionForJDBCDate("clawerTime >", value, "clawertime");
			return (Criteria) this;
		}

		public Criteria andClawertimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("clawerTime >=", value, "clawertime");
			return (Criteria) this;
		}

		public Criteria andClawertimeLessThan(Date value) {
			addCriterionForJDBCDate("clawerTime <", value, "clawertime");
			return (Criteria) this;
		}

		public Criteria andClawertimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("clawerTime <=", value, "clawertime");
			return (Criteria) this;
		}

		public Criteria andClawertimeIn(List<Date> values) {
			addCriterionForJDBCDate("clawerTime in", values, "clawertime");
			return (Criteria) this;
		}

		public Criteria andClawertimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("clawerTime not in", values, "clawertime");
			return (Criteria) this;
		}

		public Criteria andClawertimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("clawerTime between", value1, value2,
					"clawertime");
			return (Criteria) this;
		}

		public Criteria andClawertimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("clawerTime not between", value1, value2,
					"clawertime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table court_shixin_unit
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 23 11:23:29 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}