package com.unbank.mybatis.entity;

import java.util.Date;

public class ShixinUnit {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.id
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.iname
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String iname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.caseCode
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String casecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.cardNum
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String cardnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.businessEntity
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String businessentity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.courtName
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String courtname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.areaName
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String areaname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.partyTypeName
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String partytypename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.gistId
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String gistid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.regDate
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String regdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.gistUnit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String gistunit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.performance
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String performance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.disruptTypeName
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String disrupttypename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.publishDate
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String publishdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.souceid
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String souceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.clawerTime
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private Date clawertime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_shixin_unit.duty
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	private String duty;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.id
	 * @return  the value of court_shixin_unit.id
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.id
	 * @param id  the value for court_shixin_unit.id
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.iname
	 * @return  the value of court_shixin_unit.iname
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getIname() {
		return iname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.iname
	 * @param iname  the value for court_shixin_unit.iname
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setIname(String iname) {
		this.iname = iname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.caseCode
	 * @return  the value of court_shixin_unit.caseCode
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getCasecode() {
		return casecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.caseCode
	 * @param casecode  the value for court_shixin_unit.caseCode
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setCasecode(String casecode) {
		this.casecode = casecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.cardNum
	 * @return  the value of court_shixin_unit.cardNum
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getCardnum() {
		return cardnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.cardNum
	 * @param cardnum  the value for court_shixin_unit.cardNum
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setCardnum(String cardnum) {
		this.cardnum = cardnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.businessEntity
	 * @return  the value of court_shixin_unit.businessEntity
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getBusinessentity() {
		return businessentity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.businessEntity
	 * @param businessentity  the value for court_shixin_unit.businessEntity
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setBusinessentity(String businessentity) {
		this.businessentity = businessentity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.courtName
	 * @return  the value of court_shixin_unit.courtName
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getCourtname() {
		return courtname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.courtName
	 * @param courtname  the value for court_shixin_unit.courtName
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setCourtname(String courtname) {
		this.courtname = courtname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.areaName
	 * @return  the value of court_shixin_unit.areaName
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getAreaname() {
		return areaname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.areaName
	 * @param areaname  the value for court_shixin_unit.areaName
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setAreaname(String areaname) {
		this.areaname = areaname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.partyTypeName
	 * @return  the value of court_shixin_unit.partyTypeName
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getPartytypename() {
		return partytypename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.partyTypeName
	 * @param partytypename  the value for court_shixin_unit.partyTypeName
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setPartytypename(String partytypename) {
		this.partytypename = partytypename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.gistId
	 * @return  the value of court_shixin_unit.gistId
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getGistid() {
		return gistid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.gistId
	 * @param gistid  the value for court_shixin_unit.gistId
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setGistid(String gistid) {
		this.gistid = gistid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.regDate
	 * @return  the value of court_shixin_unit.regDate
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getRegdate() {
		return regdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.regDate
	 * @param regdate  the value for court_shixin_unit.regDate
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setRegdate(String regdate) {
		this.regdate = regdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.gistUnit
	 * @return  the value of court_shixin_unit.gistUnit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getGistunit() {
		return gistunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.gistUnit
	 * @param gistunit  the value for court_shixin_unit.gistUnit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setGistunit(String gistunit) {
		this.gistunit = gistunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.performance
	 * @return  the value of court_shixin_unit.performance
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getPerformance() {
		return performance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.performance
	 * @param performance  the value for court_shixin_unit.performance
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setPerformance(String performance) {
		this.performance = performance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.disruptTypeName
	 * @return  the value of court_shixin_unit.disruptTypeName
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getDisrupttypename() {
		return disrupttypename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.disruptTypeName
	 * @param disrupttypename  the value for court_shixin_unit.disruptTypeName
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setDisrupttypename(String disrupttypename) {
		this.disrupttypename = disrupttypename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.publishDate
	 * @return  the value of court_shixin_unit.publishDate
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getPublishdate() {
		return publishdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.publishDate
	 * @param publishdate  the value for court_shixin_unit.publishDate
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setPublishdate(String publishdate) {
		this.publishdate = publishdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.souceid
	 * @return  the value of court_shixin_unit.souceid
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getSouceid() {
		return souceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.souceid
	 * @param souceid  the value for court_shixin_unit.souceid
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setSouceid(String souceid) {
		this.souceid = souceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.clawerTime
	 * @return  the value of court_shixin_unit.clawerTime
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public Date getClawertime() {
		return clawertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.clawerTime
	 * @param clawertime  the value for court_shixin_unit.clawerTime
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setClawertime(Date clawertime) {
		this.clawertime = clawertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_shixin_unit.duty
	 * @return  the value of court_shixin_unit.duty
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public String getDuty() {
		return duty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_shixin_unit.duty
	 * @param duty  the value for court_shixin_unit.duty
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	public void setDuty(String duty) {
		this.duty = duty;
	}
}