package com.unbank.mybatis.entity;

import java.util.Date;

public class ShixinPro {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.id
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.iname
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String iname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.caseCode
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String casecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.age
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.sexy
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String sexy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.cardNum
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String cardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.courtName
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String courtname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.areaName
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.partyTypeName
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String partytypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.gistId
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String gistid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.regDate
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String regdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.gistUnit
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String gistunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.performance
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String performance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.disruptTypeName
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String disrupttypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.publishDate
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String publishdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.souceid
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String souceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.clawerTime
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private Date clawertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column court_shixin_pro.duty
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    private String duty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.id
     *
     * @return the value of court_shixin_pro.id
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.id
     *
     * @param id the value for court_shixin_pro.id
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.iname
     *
     * @return the value of court_shixin_pro.iname
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getIname() {
        return iname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.iname
     *
     * @param iname the value for court_shixin_pro.iname
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setIname(String iname) {
        this.iname = iname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.caseCode
     *
     * @return the value of court_shixin_pro.caseCode
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getCasecode() {
        return casecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.caseCode
     *
     * @param casecode the value for court_shixin_pro.caseCode
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setCasecode(String casecode) {
        this.casecode = casecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.age
     *
     * @return the value of court_shixin_pro.age
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.age
     *
     * @param age the value for court_shixin_pro.age
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.sexy
     *
     * @return the value of court_shixin_pro.sexy
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getSexy() {
        return sexy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.sexy
     *
     * @param sexy the value for court_shixin_pro.sexy
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setSexy(String sexy) {
        this.sexy = sexy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.cardNum
     *
     * @return the value of court_shixin_pro.cardNum
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getCardnum() {
        return cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.cardNum
     *
     * @param cardnum the value for court_shixin_pro.cardNum
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setCardnum(String cardnum) {
        this.cardnum = cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.courtName
     *
     * @return the value of court_shixin_pro.courtName
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getCourtname() {
        return courtname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.courtName
     *
     * @param courtname the value for court_shixin_pro.courtName
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setCourtname(String courtname) {
        this.courtname = courtname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.areaName
     *
     * @return the value of court_shixin_pro.areaName
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.areaName
     *
     * @param areaname the value for court_shixin_pro.areaName
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.partyTypeName
     *
     * @return the value of court_shixin_pro.partyTypeName
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getPartytypename() {
        return partytypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.partyTypeName
     *
     * @param partytypename the value for court_shixin_pro.partyTypeName
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setPartytypename(String partytypename) {
        this.partytypename = partytypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.gistId
     *
     * @return the value of court_shixin_pro.gistId
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getGistid() {
        return gistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.gistId
     *
     * @param gistid the value for court_shixin_pro.gistId
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setGistid(String gistid) {
        this.gistid = gistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.regDate
     *
     * @return the value of court_shixin_pro.regDate
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.regDate
     *
     * @param regdate the value for court_shixin_pro.regDate
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setRegdate(String regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.gistUnit
     *
     * @return the value of court_shixin_pro.gistUnit
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getGistunit() {
        return gistunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.gistUnit
     *
     * @param gistunit the value for court_shixin_pro.gistUnit
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setGistunit(String gistunit) {
        this.gistunit = gistunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.performance
     *
     * @return the value of court_shixin_pro.performance
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getPerformance() {
        return performance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.performance
     *
     * @param performance the value for court_shixin_pro.performance
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setPerformance(String performance) {
        this.performance = performance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.disruptTypeName
     *
     * @return the value of court_shixin_pro.disruptTypeName
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getDisrupttypename() {
        return disrupttypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.disruptTypeName
     *
     * @param disrupttypename the value for court_shixin_pro.disruptTypeName
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setDisrupttypename(String disrupttypename) {
        this.disrupttypename = disrupttypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.publishDate
     *
     * @return the value of court_shixin_pro.publishDate
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getPublishdate() {
        return publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.publishDate
     *
     * @param publishdate the value for court_shixin_pro.publishDate
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setPublishdate(String publishdate) {
        this.publishdate = publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.souceid
     *
     * @return the value of court_shixin_pro.souceid
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getSouceid() {
        return souceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.souceid
     *
     * @param souceid the value for court_shixin_pro.souceid
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setSouceid(String souceid) {
        this.souceid = souceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.clawerTime
     *
     * @return the value of court_shixin_pro.clawerTime
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public Date getClawertime() {
        return clawertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.clawerTime
     *
     * @param clawertime the value for court_shixin_pro.clawerTime
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setClawertime(Date clawertime) {
        this.clawertime = clawertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column court_shixin_pro.duty
     *
     * @return the value of court_shixin_pro.duty
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column court_shixin_pro.duty
     *
     * @param duty the value for court_shixin_pro.duty
     *
     * @mbggenerated Mon Nov 23 11:15:42 CST 2015
     */
    public void setDuty(String duty) {
        this.duty = duty;
    }
}