package com.unbank.mybatis.dao;

import com.unbank.mybatis.entity.ShixinUnit;
import com.unbank.mybatis.entity.ShixinUnitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShixinUnitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	int countByExample(ShixinUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	int deleteByExample(ShixinUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	int insert(ShixinUnit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	int insertSelective(ShixinUnit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	List<ShixinUnit> selectByExampleWithBLOBs(ShixinUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	List<ShixinUnit> selectByExample(ShixinUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	ShixinUnit selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ShixinUnit record,
			@Param("example") ShixinUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") ShixinUnit record,
			@Param("example") ShixinUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	int updateByExample(@Param("record") ShixinUnit record,
			@Param("example") ShixinUnitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	int updateByPrimaryKeySelective(ShixinUnit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(ShixinUnit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_shixin_unit
	 * @mbggenerated  Wed Apr 13 11:39:32 CST 2016
	 */
	int updateByPrimaryKey(ShixinUnit record);
}