package com.unbank.spider.mybatis.client;

import com.unbank.spider.mybatis.vo.ShowPoetry;
import com.unbank.spider.mybatis.vo.ShowPoetryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShowPoetryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	int countByExample(ShowPoetryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	int deleteByExample(ShowPoetryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	int insert(ShowPoetry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	int insertSelective(ShowPoetry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	List<ShowPoetry> selectByExample(ShowPoetryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	ShowPoetry selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ShowPoetry record, @Param("example") ShowPoetryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	int updateByExample(@Param("record") ShowPoetry record, @Param("example") ShowPoetryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	int updateByPrimaryKeySelective(ShowPoetry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	int updateByPrimaryKey(ShowPoetry record);
}