package com.unbank.mybatis.client;

import com.unbank.mybatis.vo.BhiPPP;
import com.unbank.mybatis.vo.BhiPPPExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.unbank.mybatis.vo.BhiPPPWithBLOBs;

public interface BhiPPPMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	int countByExample(BhiPPPExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	int deleteByExample(BhiPPPExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	int insert(BhiPPPWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	int insertSelective(BhiPPPWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	List<BhiPPPWithBLOBs> selectByExampleWithBLOBs(BhiPPPExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	List<BhiPPP> selectByExample(BhiPPPExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	BhiPPPWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	int updateByExampleSelective(@Param("record") BhiPPPWithBLOBs record,
			@Param("example") BhiPPPExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") BhiPPPWithBLOBs record,
			@Param("example") BhiPPPExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	int updateByExample(@Param("record") BhiPPP record,
			@Param("example") BhiPPPExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	int updateByPrimaryKeySelective(BhiPPPWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	int updateByPrimaryKeyWithBLOBs(BhiPPPWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bhi_ppp
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	int updateByPrimaryKey(BhiPPP record);
}