package com.unbank.mybatis.client;

import com.unbank.mybatis.vo.BhiPppWord;
import com.unbank.mybatis.vo.BhiPppWordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BhiPppWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    int countByExample(BhiPppWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    int deleteByExample(BhiPppWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer pppId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    int insert(BhiPppWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    int insertSelective(BhiPppWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    List<BhiPppWord> selectByExample(BhiPppWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    BhiPppWord selectByPrimaryKey(Integer pppId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") BhiPppWord record, @Param("example") BhiPppWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    int updateByExample(@Param("record") BhiPppWord record, @Param("example") BhiPppWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(BhiPppWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    int updateByPrimaryKey(BhiPppWord record);
}