package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.PtfDayNumWeb;
import com.unbank.mybatis.entity.PtfDayNumWebExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PtfDayNumWebMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_web
     *
     * @mbggenerated Wed Aug 19 09:37:11 GMT+08:00 2015
     */
    int countByExample(PtfDayNumWebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_web
     *
     * @mbggenerated Wed Aug 19 09:37:11 GMT+08:00 2015
     */
    int deleteByExample(PtfDayNumWebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_web
     *
     * @mbggenerated Wed Aug 19 09:37:11 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer numId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_web
     *
     * @mbggenerated Wed Aug 19 09:37:11 GMT+08:00 2015
     */
    int insert(PtfDayNumWeb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_web
     *
     * @mbggenerated Wed Aug 19 09:37:11 GMT+08:00 2015
     */
    int insertSelective(PtfDayNumWeb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_web
     *
     * @mbggenerated Wed Aug 19 09:37:11 GMT+08:00 2015
     */
    List<PtfDayNumWeb> selectByExample(PtfDayNumWebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_web
     *
     * @mbggenerated Wed Aug 19 09:37:11 GMT+08:00 2015
     */
    PtfDayNumWeb selectByPrimaryKey(Integer numId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_web
     *
     * @mbggenerated Wed Aug 19 09:37:11 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") PtfDayNumWeb record, @Param("example") PtfDayNumWebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_web
     *
     * @mbggenerated Wed Aug 19 09:37:11 GMT+08:00 2015
     */
    int updateByExample(@Param("record") PtfDayNumWeb record, @Param("example") PtfDayNumWebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_web
     *
     * @mbggenerated Wed Aug 19 09:37:11 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(PtfDayNumWeb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num_web
     *
     * @mbggenerated Wed Aug 19 09:37:11 GMT+08:00 2015
     */
    int updateByPrimaryKey(PtfDayNumWeb record);
}