package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.WebsitePaser;
import com.unbank.mybatis.entity.WebsitePaserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsitePaserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Aug 19 09:42:33 GMT+08:00 2015
     */
    int countByExample(WebsitePaserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Aug 19 09:42:33 GMT+08:00 2015
     */
    int deleteByExample(WebsitePaserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Aug 19 09:42:33 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer parserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Aug 19 09:42:33 GMT+08:00 2015
     */
    int insert(WebsitePaser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Aug 19 09:42:33 GMT+08:00 2015
     */
    int insertSelective(WebsitePaser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Aug 19 09:42:33 GMT+08:00 2015
     */
    List<WebsitePaser> selectByExample(WebsitePaserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Aug 19 09:42:33 GMT+08:00 2015
     */
    WebsitePaser selectByPrimaryKey(Integer parserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Aug 19 09:42:33 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") WebsitePaser record, @Param("example") WebsitePaserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Aug 19 09:42:33 GMT+08:00 2015
     */
    int updateByExample(@Param("record") WebsitePaser record, @Param("example") WebsitePaserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Aug 19 09:42:33 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(WebsitePaser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Wed Aug 19 09:42:33 GMT+08:00 2015
     */
    int updateByPrimaryKey(WebsitePaser record);
}