package com.unbank.spider.mybatis.vo;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.util.Iterator;

public class ShowPoetryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public ShowPoetryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andNewstimeIsNull() {
			addCriterion("newstime is null");
			return (Criteria) this;
		}

		public Criteria andNewstimeIsNotNull() {
			addCriterion("newstime is not null");
			return (Criteria) this;
		}

		public Criteria andNewstimeEqualTo(Date value) {
			addCriterionForJDBCDate("newstime =", value, "newstime");
			return (Criteria) this;
		}

		public Criteria andNewstimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("newstime <>", value, "newstime");
			return (Criteria) this;
		}

		public Criteria andNewstimeGreaterThan(Date value) {
			addCriterionForJDBCDate("newstime >", value, "newstime");
			return (Criteria) this;
		}

		public Criteria andNewstimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("newstime >=", value, "newstime");
			return (Criteria) this;
		}

		public Criteria andNewstimeLessThan(Date value) {
			addCriterionForJDBCDate("newstime <", value, "newstime");
			return (Criteria) this;
		}

		public Criteria andNewstimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("newstime <=", value, "newstime");
			return (Criteria) this;
		}

		public Criteria andNewstimeIn(List<Date> values) {
			addCriterionForJDBCDate("newstime in", values, "newstime");
			return (Criteria) this;
		}

		public Criteria andNewstimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("newstime not in", values, "newstime");
			return (Criteria) this;
		}

		public Criteria andNewstimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("newstime between", value1, value2, "newstime");
			return (Criteria) this;
		}

		public Criteria andNewstimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("newstime not between", value1, value2, "newstime");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNull() {
			addCriterion("author is null");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNotNull() {
			addCriterion("author is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorEqualTo(String value) {
			addCriterion("author =", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotEqualTo(String value) {
			addCriterion("author <>", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThan(String value) {
			addCriterion("author >", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThanOrEqualTo(String value) {
			addCriterion("author >=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThan(String value) {
			addCriterion("author <", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThanOrEqualTo(String value) {
			addCriterion("author <=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLike(String value) {
			addCriterion("author like", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotLike(String value) {
			addCriterion("author not like", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorIn(List<String> values) {
			addCriterion("author in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotIn(List<String> values) {
			addCriterion("author not in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorBetween(String value1, String value2) {
			addCriterion("author between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotBetween(String value1, String value2) {
			addCriterion("author not between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andSourceIsNull() {
			addCriterion("source is null");
			return (Criteria) this;
		}

		public Criteria andSourceIsNotNull() {
			addCriterion("source is not null");
			return (Criteria) this;
		}

		public Criteria andSourceEqualTo(String value) {
			addCriterion("source =", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceNotEqualTo(String value) {
			addCriterion("source <>", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceGreaterThan(String value) {
			addCriterion("source >", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceGreaterThanOrEqualTo(String value) {
			addCriterion("source >=", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceLessThan(String value) {
			addCriterion("source <", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceLessThanOrEqualTo(String value) {
			addCriterion("source <=", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceLike(String value) {
			addCriterion("source like", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceNotLike(String value) {
			addCriterion("source not like", value, "source");
			return (Criteria) this;
		}

		public Criteria andSourceIn(List<String> values) {
			addCriterion("source in", values, "source");
			return (Criteria) this;
		}

		public Criteria andSourceNotIn(List<String> values) {
			addCriterion("source not in", values, "source");
			return (Criteria) this;
		}

		public Criteria andSourceBetween(String value1, String value2) {
			addCriterion("source between", value1, value2, "source");
			return (Criteria) this;
		}

		public Criteria andSourceNotBetween(String value1, String value2) {
			addCriterion("source not between", value1, value2, "source");
			return (Criteria) this;
		}

		public Criteria andBriefIsNull() {
			addCriterion("brief is null");
			return (Criteria) this;
		}

		public Criteria andBriefIsNotNull() {
			addCriterion("brief is not null");
			return (Criteria) this;
		}

		public Criteria andBriefEqualTo(String value) {
			addCriterion("brief =", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefNotEqualTo(String value) {
			addCriterion("brief <>", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefGreaterThan(String value) {
			addCriterion("brief >", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefGreaterThanOrEqualTo(String value) {
			addCriterion("brief >=", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefLessThan(String value) {
			addCriterion("brief <", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefLessThanOrEqualTo(String value) {
			addCriterion("brief <=", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefLike(String value) {
			addCriterion("brief like", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefNotLike(String value) {
			addCriterion("brief not like", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefIn(List<String> values) {
			addCriterion("brief in", values, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefNotIn(List<String> values) {
			addCriterion("brief not in", values, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefBetween(String value1, String value2) {
			addCriterion("brief between", value1, value2, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefNotBetween(String value1, String value2) {
			addCriterion("brief not between", value1, value2, "brief");
			return (Criteria) this;
		}

		public Criteria andReIsNull() {
			addCriterion("re is null");
			return (Criteria) this;
		}

		public Criteria andReIsNotNull() {
			addCriterion("re is not null");
			return (Criteria) this;
		}

		public Criteria andReEqualTo(String value) {
			addCriterion("re =", value, "re");
			return (Criteria) this;
		}

		public Criteria andReNotEqualTo(String value) {
			addCriterion("re <>", value, "re");
			return (Criteria) this;
		}

		public Criteria andReGreaterThan(String value) {
			addCriterion("re >", value, "re");
			return (Criteria) this;
		}

		public Criteria andReGreaterThanOrEqualTo(String value) {
			addCriterion("re >=", value, "re");
			return (Criteria) this;
		}

		public Criteria andReLessThan(String value) {
			addCriterion("re <", value, "re");
			return (Criteria) this;
		}

		public Criteria andReLessThanOrEqualTo(String value) {
			addCriterion("re <=", value, "re");
			return (Criteria) this;
		}

		public Criteria andReLike(String value) {
			addCriterion("re like", value, "re");
			return (Criteria) this;
		}

		public Criteria andReNotLike(String value) {
			addCriterion("re not like", value, "re");
			return (Criteria) this;
		}

		public Criteria andReIn(List<String> values) {
			addCriterion("re in", values, "re");
			return (Criteria) this;
		}

		public Criteria andReNotIn(List<String> values) {
			addCriterion("re not in", values, "re");
			return (Criteria) this;
		}

		public Criteria andReBetween(String value1, String value2) {
			addCriterion("re between", value1, value2, "re");
			return (Criteria) this;
		}

		public Criteria andReNotBetween(String value1, String value2) {
			addCriterion("re not between", value1, value2, "re");
			return (Criteria) this;
		}

		public Criteria andDetailurlIsNull() {
			addCriterion("detailurl is null");
			return (Criteria) this;
		}

		public Criteria andDetailurlIsNotNull() {
			addCriterion("detailurl is not null");
			return (Criteria) this;
		}

		public Criteria andDetailurlEqualTo(String value) {
			addCriterion("detailurl =", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlNotEqualTo(String value) {
			addCriterion("detailurl <>", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlGreaterThan(String value) {
			addCriterion("detailurl >", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlGreaterThanOrEqualTo(String value) {
			addCriterion("detailurl >=", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlLessThan(String value) {
			addCriterion("detailurl <", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlLessThanOrEqualTo(String value) {
			addCriterion("detailurl <=", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlLike(String value) {
			addCriterion("detailurl like", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlNotLike(String value) {
			addCriterion("detailurl not like", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlIn(List<String> values) {
			addCriterion("detailurl in", values, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlNotIn(List<String> values) {
			addCriterion("detailurl not in", values, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlBetween(String value1, String value2) {
			addCriterion("detailurl between", value1, value2, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlNotBetween(String value1, String value2) {
			addCriterion("detailurl not between", value1, value2, "detailurl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table show_poetry
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table show_poetry
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 14 10:21:48 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}