package com.unbank.spider.mybatis.vo;

public class ShowTag {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_tag.id
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_tag.tagname
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	private String tagname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_tag.id
	 * @return  the value of show_tag.id
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_tag.id
	 * @param id  the value for show_tag.id
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_tag.tagname
	 * @return  the value of show_tag.tagname
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public String getTagname() {
		return tagname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_tag.tagname
	 * @param tagname  the value for show_tag.tagname
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setTagname(String tagname) {
		this.tagname = tagname;
	}
}