package com.unbank.spider.mybatis.vo;

import java.util.Date;

public class ShowPoetry {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_poetry.id
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_poetry.title
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_poetry.newstime
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	private Date newstime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_poetry.author
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_poetry.source
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	private String source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_poetry.brief
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	private String brief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_poetry.re
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	private String re;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_poetry.detailurl
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	private String detailurl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_poetry.id
	 * @return  the value of show_poetry.id
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_poetry.id
	 * @param id  the value for show_poetry.id
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_poetry.title
	 * @return  the value of show_poetry.title
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_poetry.title
	 * @param title  the value for show_poetry.title
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_poetry.newstime
	 * @return  the value of show_poetry.newstime
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public Date getNewstime() {
		return newstime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_poetry.newstime
	 * @param newstime  the value for show_poetry.newstime
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setNewstime(Date newstime) {
		this.newstime = newstime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_poetry.author
	 * @return  the value of show_poetry.author
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_poetry.author
	 * @param author  the value for show_poetry.author
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_poetry.source
	 * @return  the value of show_poetry.source
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_poetry.source
	 * @param source  the value for show_poetry.source
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setSource(String source) {
		this.source = source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_poetry.brief
	 * @return  the value of show_poetry.brief
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public String getBrief() {
		return brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_poetry.brief
	 * @param brief  the value for show_poetry.brief
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setBrief(String brief) {
		this.brief = brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_poetry.re
	 * @return  the value of show_poetry.re
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public String getRe() {
		return re;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_poetry.re
	 * @param re  the value for show_poetry.re
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setRe(String re) {
		this.re = re;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_poetry.detailurl
	 * @return  the value of show_poetry.detailurl
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public String getDetailurl() {
		return detailurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_poetry.detailurl
	 * @param detailurl  the value for show_poetry.detailurl
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setDetailurl(String detailurl) {
		this.detailurl = detailurl;
	}
}