package com.unbank.spider.mybatis.vo;

public class ShowPoetryText {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_poetry_text.id
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_poetry_text.text
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	private String text;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_poetry_text.id
	 * @return  the value of show_poetry_text.id
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_poetry_text.id
	 * @param id  the value for show_poetry_text.id
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_poetry_text.text
	 * @return  the value of show_poetry_text.text
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_poetry_text.text
	 * @param text  the value for show_poetry_text.text
	 * @mbggenerated  Wed May 31 17:14:13 CST 2017
	 */
	public void setText(String text) {
		this.text = text;
	}
}