package com.unbank.spider.mybatis.vo;

import java.util.Date;

public class ShowTitle {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_title.id
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_title.title
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_title.pubdate
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	private Date pubdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_title.tid
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	private String tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_title.url
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_title.brief
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	private String brief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_title.picurl
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	private String picurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column show_title.praise
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	private Integer praise;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_title.id
	 * @return  the value of show_title.id
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_title.id
	 * @param id  the value for show_title.id
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_title.title
	 * @return  the value of show_title.title
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_title.title
	 * @param title  the value for show_title.title
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_title.pubdate
	 * @return  the value of show_title.pubdate
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public Date getPubdate() {
		return pubdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_title.pubdate
	 * @param pubdate  the value for show_title.pubdate
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public void setPubdate(Date pubdate) {
		this.pubdate = pubdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_title.tid
	 * @return  the value of show_title.tid
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public String getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_title.tid
	 * @param tid  the value for show_title.tid
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public void setTid(String tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_title.url
	 * @return  the value of show_title.url
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_title.url
	 * @param url  the value for show_title.url
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_title.brief
	 * @return  the value of show_title.brief
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public String getBrief() {
		return brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_title.brief
	 * @param brief  the value for show_title.brief
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public void setBrief(String brief) {
		this.brief = brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_title.picurl
	 * @return  the value of show_title.picurl
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public String getPicurl() {
		return picurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_title.picurl
	 * @param picurl  the value for show_title.picurl
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public void setPicurl(String picurl) {
		this.picurl = picurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column show_title.praise
	 * @return  the value of show_title.praise
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public Integer getPraise() {
		return praise;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column show_title.praise
	 * @param praise  the value for show_title.praise
	 * @mbggenerated  Tue Jun 06 17:07:54 CST 2017
	 */
	public void setPraise(Integer praise) {
		this.praise = praise;
	}
}