package com.unbank.mybatis.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class BhiPppWordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public BhiPppWordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andPppIdIsNull() {
            addCriterion("ppp_id is null");
            return (Criteria) this;
        }

        public Criteria andPppIdIsNotNull() {
            addCriterion("ppp_id is not null");
            return (Criteria) this;
        }

        public Criteria andPppIdEqualTo(Integer value) {
            addCriterion("ppp_id =", value, "pppId");
            return (Criteria) this;
        }

        public Criteria andPppIdNotEqualTo(Integer value) {
            addCriterion("ppp_id <>", value, "pppId");
            return (Criteria) this;
        }

        public Criteria andPppIdGreaterThan(Integer value) {
            addCriterion("ppp_id >", value, "pppId");
            return (Criteria) this;
        }

        public Criteria andPppIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ppp_id >=", value, "pppId");
            return (Criteria) this;
        }

        public Criteria andPppIdLessThan(Integer value) {
            addCriterion("ppp_id <", value, "pppId");
            return (Criteria) this;
        }

        public Criteria andPppIdLessThanOrEqualTo(Integer value) {
            addCriterion("ppp_id <=", value, "pppId");
            return (Criteria) this;
        }

        public Criteria andPppIdIn(List<Integer> values) {
            addCriterion("ppp_id in", values, "pppId");
            return (Criteria) this;
        }

        public Criteria andPppIdNotIn(List<Integer> values) {
            addCriterion("ppp_id not in", values, "pppId");
            return (Criteria) this;
        }

        public Criteria andPppIdBetween(Integer value1, Integer value2) {
            addCriterion("ppp_id between", value1, value2, "pppId");
            return (Criteria) this;
        }

        public Criteria andPppIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ppp_id not between", value1, value2, "pppId");
            return (Criteria) this;
        }

        public Criteria andPppNameIsNull() {
            addCriterion("ppp_name is null");
            return (Criteria) this;
        }

        public Criteria andPppNameIsNotNull() {
            addCriterion("ppp_name is not null");
            return (Criteria) this;
        }

        public Criteria andPppNameEqualTo(String value) {
            addCriterion("ppp_name =", value, "pppName");
            return (Criteria) this;
        }

        public Criteria andPppNameNotEqualTo(String value) {
            addCriterion("ppp_name <>", value, "pppName");
            return (Criteria) this;
        }

        public Criteria andPppNameGreaterThan(String value) {
            addCriterion("ppp_name >", value, "pppName");
            return (Criteria) this;
        }

        public Criteria andPppNameGreaterThanOrEqualTo(String value) {
            addCriterion("ppp_name >=", value, "pppName");
            return (Criteria) this;
        }

        public Criteria andPppNameLessThan(String value) {
            addCriterion("ppp_name <", value, "pppName");
            return (Criteria) this;
        }

        public Criteria andPppNameLessThanOrEqualTo(String value) {
            addCriterion("ppp_name <=", value, "pppName");
            return (Criteria) this;
        }

        public Criteria andPppNameLike(String value) {
            addCriterion("ppp_name like", value, "pppName");
            return (Criteria) this;
        }

        public Criteria andPppNameNotLike(String value) {
            addCriterion("ppp_name not like", value, "pppName");
            return (Criteria) this;
        }

        public Criteria andPppNameIn(List<String> values) {
            addCriterion("ppp_name in", values, "pppName");
            return (Criteria) this;
        }

        public Criteria andPppNameNotIn(List<String> values) {
            addCriterion("ppp_name not in", values, "pppName");
            return (Criteria) this;
        }

        public Criteria andPppNameBetween(String value1, String value2) {
            addCriterion("ppp_name between", value1, value2, "pppName");
            return (Criteria) this;
        }

        public Criteria andPppNameNotBetween(String value1, String value2) {
            addCriterion("ppp_name not between", value1, value2, "pppName");
            return (Criteria) this;
        }

        public Criteria andPppRegionIsNull() {
            addCriterion("ppp_region is null");
            return (Criteria) this;
        }

        public Criteria andPppRegionIsNotNull() {
            addCriterion("ppp_region is not null");
            return (Criteria) this;
        }

        public Criteria andPppRegionEqualTo(String value) {
            addCriterion("ppp_region =", value, "pppRegion");
            return (Criteria) this;
        }

        public Criteria andPppRegionNotEqualTo(String value) {
            addCriterion("ppp_region <>", value, "pppRegion");
            return (Criteria) this;
        }

        public Criteria andPppRegionGreaterThan(String value) {
            addCriterion("ppp_region >", value, "pppRegion");
            return (Criteria) this;
        }

        public Criteria andPppRegionGreaterThanOrEqualTo(String value) {
            addCriterion("ppp_region >=", value, "pppRegion");
            return (Criteria) this;
        }

        public Criteria andPppRegionLessThan(String value) {
            addCriterion("ppp_region <", value, "pppRegion");
            return (Criteria) this;
        }

        public Criteria andPppRegionLessThanOrEqualTo(String value) {
            addCriterion("ppp_region <=", value, "pppRegion");
            return (Criteria) this;
        }

        public Criteria andPppRegionLike(String value) {
            addCriterion("ppp_region like", value, "pppRegion");
            return (Criteria) this;
        }

        public Criteria andPppRegionNotLike(String value) {
            addCriterion("ppp_region not like", value, "pppRegion");
            return (Criteria) this;
        }

        public Criteria andPppRegionIn(List<String> values) {
            addCriterion("ppp_region in", values, "pppRegion");
            return (Criteria) this;
        }

        public Criteria andPppRegionNotIn(List<String> values) {
            addCriterion("ppp_region not in", values, "pppRegion");
            return (Criteria) this;
        }

        public Criteria andPppRegionBetween(String value1, String value2) {
            addCriterion("ppp_region between", value1, value2, "pppRegion");
            return (Criteria) this;
        }

        public Criteria andPppRegionNotBetween(String value1, String value2) {
            addCriterion("ppp_region not between", value1, value2, "pppRegion");
            return (Criteria) this;
        }

        public Criteria andPppAreaIsNull() {
            addCriterion("ppp_area is null");
            return (Criteria) this;
        }

        public Criteria andPppAreaIsNotNull() {
            addCriterion("ppp_area is not null");
            return (Criteria) this;
        }

        public Criteria andPppAreaEqualTo(String value) {
            addCriterion("ppp_area =", value, "pppArea");
            return (Criteria) this;
        }

        public Criteria andPppAreaNotEqualTo(String value) {
            addCriterion("ppp_area <>", value, "pppArea");
            return (Criteria) this;
        }

        public Criteria andPppAreaGreaterThan(String value) {
            addCriterion("ppp_area >", value, "pppArea");
            return (Criteria) this;
        }

        public Criteria andPppAreaGreaterThanOrEqualTo(String value) {
            addCriterion("ppp_area >=", value, "pppArea");
            return (Criteria) this;
        }

        public Criteria andPppAreaLessThan(String value) {
            addCriterion("ppp_area <", value, "pppArea");
            return (Criteria) this;
        }

        public Criteria andPppAreaLessThanOrEqualTo(String value) {
            addCriterion("ppp_area <=", value, "pppArea");
            return (Criteria) this;
        }

        public Criteria andPppAreaLike(String value) {
            addCriterion("ppp_area like", value, "pppArea");
            return (Criteria) this;
        }

        public Criteria andPppAreaNotLike(String value) {
            addCriterion("ppp_area not like", value, "pppArea");
            return (Criteria) this;
        }

        public Criteria andPppAreaIn(List<String> values) {
            addCriterion("ppp_area in", values, "pppArea");
            return (Criteria) this;
        }

        public Criteria andPppAreaNotIn(List<String> values) {
            addCriterion("ppp_area not in", values, "pppArea");
            return (Criteria) this;
        }

        public Criteria andPppAreaBetween(String value1, String value2) {
            addCriterion("ppp_area between", value1, value2, "pppArea");
            return (Criteria) this;
        }

        public Criteria andPppAreaNotBetween(String value1, String value2) {
            addCriterion("ppp_area not between", value1, value2, "pppArea");
            return (Criteria) this;
        }

        public Criteria andPppIndIsNull() {
            addCriterion("ppp_ind is null");
            return (Criteria) this;
        }

        public Criteria andPppIndIsNotNull() {
            addCriterion("ppp_ind is not null");
            return (Criteria) this;
        }

        public Criteria andPppIndEqualTo(String value) {
            addCriterion("ppp_ind =", value, "pppInd");
            return (Criteria) this;
        }

        public Criteria andPppIndNotEqualTo(String value) {
            addCriterion("ppp_ind <>", value, "pppInd");
            return (Criteria) this;
        }

        public Criteria andPppIndGreaterThan(String value) {
            addCriterion("ppp_ind >", value, "pppInd");
            return (Criteria) this;
        }

        public Criteria andPppIndGreaterThanOrEqualTo(String value) {
            addCriterion("ppp_ind >=", value, "pppInd");
            return (Criteria) this;
        }

        public Criteria andPppIndLessThan(String value) {
            addCriterion("ppp_ind <", value, "pppInd");
            return (Criteria) this;
        }

        public Criteria andPppIndLessThanOrEqualTo(String value) {
            addCriterion("ppp_ind <=", value, "pppInd");
            return (Criteria) this;
        }

        public Criteria andPppIndLike(String value) {
            addCriterion("ppp_ind like", value, "pppInd");
            return (Criteria) this;
        }

        public Criteria andPppIndNotLike(String value) {
            addCriterion("ppp_ind not like", value, "pppInd");
            return (Criteria) this;
        }

        public Criteria andPppIndIn(List<String> values) {
            addCriterion("ppp_ind in", values, "pppInd");
            return (Criteria) this;
        }

        public Criteria andPppIndNotIn(List<String> values) {
            addCriterion("ppp_ind not in", values, "pppInd");
            return (Criteria) this;
        }

        public Criteria andPppIndBetween(String value1, String value2) {
            addCriterion("ppp_ind between", value1, value2, "pppInd");
            return (Criteria) this;
        }

        public Criteria andPppIndNotBetween(String value1, String value2) {
            addCriterion("ppp_ind not between", value1, value2, "pppInd");
            return (Criteria) this;
        }

        public Criteria andPppTypeIsNull() {
            addCriterion("ppp_type is null");
            return (Criteria) this;
        }

        public Criteria andPppTypeIsNotNull() {
            addCriterion("ppp_type is not null");
            return (Criteria) this;
        }

        public Criteria andPppTypeEqualTo(String value) {
            addCriterion("ppp_type =", value, "pppType");
            return (Criteria) this;
        }

        public Criteria andPppTypeNotEqualTo(String value) {
            addCriterion("ppp_type <>", value, "pppType");
            return (Criteria) this;
        }

        public Criteria andPppTypeGreaterThan(String value) {
            addCriterion("ppp_type >", value, "pppType");
            return (Criteria) this;
        }

        public Criteria andPppTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ppp_type >=", value, "pppType");
            return (Criteria) this;
        }

        public Criteria andPppTypeLessThan(String value) {
            addCriterion("ppp_type <", value, "pppType");
            return (Criteria) this;
        }

        public Criteria andPppTypeLessThanOrEqualTo(String value) {
            addCriterion("ppp_type <=", value, "pppType");
            return (Criteria) this;
        }

        public Criteria andPppTypeLike(String value) {
            addCriterion("ppp_type like", value, "pppType");
            return (Criteria) this;
        }

        public Criteria andPppTypeNotLike(String value) {
            addCriterion("ppp_type not like", value, "pppType");
            return (Criteria) this;
        }

        public Criteria andPppTypeIn(List<String> values) {
            addCriterion("ppp_type in", values, "pppType");
            return (Criteria) this;
        }

        public Criteria andPppTypeNotIn(List<String> values) {
            addCriterion("ppp_type not in", values, "pppType");
            return (Criteria) this;
        }

        public Criteria andPppTypeBetween(String value1, String value2) {
            addCriterion("ppp_type between", value1, value2, "pppType");
            return (Criteria) this;
        }

        public Criteria andPppTypeNotBetween(String value1, String value2) {
            addCriterion("ppp_type not between", value1, value2, "pppType");
            return (Criteria) this;
        }

        public Criteria andPppModelIsNull() {
            addCriterion("ppp_model is null");
            return (Criteria) this;
        }

        public Criteria andPppModelIsNotNull() {
            addCriterion("ppp_model is not null");
            return (Criteria) this;
        }

        public Criteria andPppModelEqualTo(String value) {
            addCriterion("ppp_model =", value, "pppModel");
            return (Criteria) this;
        }

        public Criteria andPppModelNotEqualTo(String value) {
            addCriterion("ppp_model <>", value, "pppModel");
            return (Criteria) this;
        }

        public Criteria andPppModelGreaterThan(String value) {
            addCriterion("ppp_model >", value, "pppModel");
            return (Criteria) this;
        }

        public Criteria andPppModelGreaterThanOrEqualTo(String value) {
            addCriterion("ppp_model >=", value, "pppModel");
            return (Criteria) this;
        }

        public Criteria andPppModelLessThan(String value) {
            addCriterion("ppp_model <", value, "pppModel");
            return (Criteria) this;
        }

        public Criteria andPppModelLessThanOrEqualTo(String value) {
            addCriterion("ppp_model <=", value, "pppModel");
            return (Criteria) this;
        }

        public Criteria andPppModelLike(String value) {
            addCriterion("ppp_model like", value, "pppModel");
            return (Criteria) this;
        }

        public Criteria andPppModelNotLike(String value) {
            addCriterion("ppp_model not like", value, "pppModel");
            return (Criteria) this;
        }

        public Criteria andPppModelIn(List<String> values) {
            addCriterion("ppp_model in", values, "pppModel");
            return (Criteria) this;
        }

        public Criteria andPppModelNotIn(List<String> values) {
            addCriterion("ppp_model not in", values, "pppModel");
            return (Criteria) this;
        }

        public Criteria andPppModelBetween(String value1, String value2) {
            addCriterion("ppp_model between", value1, value2, "pppModel");
            return (Criteria) this;
        }

        public Criteria andPppModelNotBetween(String value1, String value2) {
            addCriterion("ppp_model not between", value1, value2, "pppModel");
            return (Criteria) this;
        }

        public Criteria andPppAssetsIsNull() {
            addCriterion("ppp_assets is null");
            return (Criteria) this;
        }

        public Criteria andPppAssetsIsNotNull() {
            addCriterion("ppp_assets is not null");
            return (Criteria) this;
        }

        public Criteria andPppAssetsEqualTo(Double value) {
            addCriterion("ppp_assets =", value, "pppAssets");
            return (Criteria) this;
        }

        public Criteria andPppAssetsNotEqualTo(Double value) {
            addCriterion("ppp_assets <>", value, "pppAssets");
            return (Criteria) this;
        }

        public Criteria andPppAssetsGreaterThan(Double value) {
            addCriterion("ppp_assets >", value, "pppAssets");
            return (Criteria) this;
        }

        public Criteria andPppAssetsGreaterThanOrEqualTo(Double value) {
            addCriterion("ppp_assets >=", value, "pppAssets");
            return (Criteria) this;
        }

        public Criteria andPppAssetsLessThan(Double value) {
            addCriterion("ppp_assets <", value, "pppAssets");
            return (Criteria) this;
        }

        public Criteria andPppAssetsLessThanOrEqualTo(Double value) {
            addCriterion("ppp_assets <=", value, "pppAssets");
            return (Criteria) this;
        }

        public Criteria andPppAssetsIn(List<Double> values) {
            addCriterion("ppp_assets in", values, "pppAssets");
            return (Criteria) this;
        }

        public Criteria andPppAssetsNotIn(List<Double> values) {
            addCriterion("ppp_assets not in", values, "pppAssets");
            return (Criteria) this;
        }

        public Criteria andPppAssetsBetween(Double value1, Double value2) {
            addCriterion("ppp_assets between", value1, value2, "pppAssets");
            return (Criteria) this;
        }

        public Criteria andPppAssetsNotBetween(Double value1, Double value2) {
            addCriterion("ppp_assets not between", value1, value2, "pppAssets");
            return (Criteria) this;
        }

        public Criteria andPppLevelIsNull() {
            addCriterion("ppp_level is null");
            return (Criteria) this;
        }

        public Criteria andPppLevelIsNotNull() {
            addCriterion("ppp_level is not null");
            return (Criteria) this;
        }

        public Criteria andPppLevelEqualTo(String value) {
            addCriterion("ppp_level =", value, "pppLevel");
            return (Criteria) this;
        }

        public Criteria andPppLevelNotEqualTo(String value) {
            addCriterion("ppp_level <>", value, "pppLevel");
            return (Criteria) this;
        }

        public Criteria andPppLevelGreaterThan(String value) {
            addCriterion("ppp_level >", value, "pppLevel");
            return (Criteria) this;
        }

        public Criteria andPppLevelGreaterThanOrEqualTo(String value) {
            addCriterion("ppp_level >=", value, "pppLevel");
            return (Criteria) this;
        }

        public Criteria andPppLevelLessThan(String value) {
            addCriterion("ppp_level <", value, "pppLevel");
            return (Criteria) this;
        }

        public Criteria andPppLevelLessThanOrEqualTo(String value) {
            addCriterion("ppp_level <=", value, "pppLevel");
            return (Criteria) this;
        }

        public Criteria andPppLevelLike(String value) {
            addCriterion("ppp_level like", value, "pppLevel");
            return (Criteria) this;
        }

        public Criteria andPppLevelNotLike(String value) {
            addCriterion("ppp_level not like", value, "pppLevel");
            return (Criteria) this;
        }

        public Criteria andPppLevelIn(List<String> values) {
            addCriterion("ppp_level in", values, "pppLevel");
            return (Criteria) this;
        }

        public Criteria andPppLevelNotIn(List<String> values) {
            addCriterion("ppp_level not in", values, "pppLevel");
            return (Criteria) this;
        }

        public Criteria andPppLevelBetween(String value1, String value2) {
            addCriterion("ppp_level between", value1, value2, "pppLevel");
            return (Criteria) this;
        }

        public Criteria andPppLevelNotBetween(String value1, String value2) {
            addCriterion("ppp_level not between", value1, value2, "pppLevel");
            return (Criteria) this;
        }

        public Criteria andPppUtimeIsNull() {
            addCriterion("ppp_utime is null");
            return (Criteria) this;
        }

        public Criteria andPppUtimeIsNotNull() {
            addCriterion("ppp_utime is not null");
            return (Criteria) this;
        }

        public Criteria andPppUtimeEqualTo(Date value) {
            addCriterionForJDBCDate("ppp_utime =", value, "pppUtime");
            return (Criteria) this;
        }

        public Criteria andPppUtimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("ppp_utime <>", value, "pppUtime");
            return (Criteria) this;
        }

        public Criteria andPppUtimeGreaterThan(Date value) {
            addCriterionForJDBCDate("ppp_utime >", value, "pppUtime");
            return (Criteria) this;
        }

        public Criteria andPppUtimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ppp_utime >=", value, "pppUtime");
            return (Criteria) this;
        }

        public Criteria andPppUtimeLessThan(Date value) {
            addCriterionForJDBCDate("ppp_utime <", value, "pppUtime");
            return (Criteria) this;
        }

        public Criteria andPppUtimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ppp_utime <=", value, "pppUtime");
            return (Criteria) this;
        }

        public Criteria andPppUtimeIn(List<Date> values) {
            addCriterionForJDBCDate("ppp_utime in", values, "pppUtime");
            return (Criteria) this;
        }

        public Criteria andPppUtimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("ppp_utime not in", values, "pppUtime");
            return (Criteria) this;
        }

        public Criteria andPppUtimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ppp_utime between", value1, value2, "pppUtime");
            return (Criteria) this;
        }

        public Criteria andPppUtimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ppp_utime not between", value1, value2, "pppUtime");
            return (Criteria) this;
        }

        public Criteria andPppItimeIsNull() {
            addCriterion("ppp_itime is null");
            return (Criteria) this;
        }

        public Criteria andPppItimeIsNotNull() {
            addCriterion("ppp_itime is not null");
            return (Criteria) this;
        }

        public Criteria andPppItimeEqualTo(Date value) {
            addCriterionForJDBCDate("ppp_itime =", value, "pppItime");
            return (Criteria) this;
        }

        public Criteria andPppItimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("ppp_itime <>", value, "pppItime");
            return (Criteria) this;
        }

        public Criteria andPppItimeGreaterThan(Date value) {
            addCriterionForJDBCDate("ppp_itime >", value, "pppItime");
            return (Criteria) this;
        }

        public Criteria andPppItimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ppp_itime >=", value, "pppItime");
            return (Criteria) this;
        }

        public Criteria andPppItimeLessThan(Date value) {
            addCriterionForJDBCDate("ppp_itime <", value, "pppItime");
            return (Criteria) this;
        }

        public Criteria andPppItimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ppp_itime <=", value, "pppItime");
            return (Criteria) this;
        }

        public Criteria andPppItimeIn(List<Date> values) {
            addCriterionForJDBCDate("ppp_itime in", values, "pppItime");
            return (Criteria) this;
        }

        public Criteria andPppItimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("ppp_itime not in", values, "pppItime");
            return (Criteria) this;
        }

        public Criteria andPppItimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ppp_itime between", value1, value2, "pppItime");
            return (Criteria) this;
        }

        public Criteria andPppItimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ppp_itime not between", value1, value2, "pppItime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bhi_ppp_word
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}