package com.unbank.mybatis.vo;

import java.util.Date;

public class BhiPppWord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp_word.ppp_id
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    private Integer pppId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp_word.ppp_name
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    private String pppName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp_word.ppp_region
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    private String pppRegion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp_word.ppp_area
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    private String pppArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp_word.ppp_ind
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    private String pppInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp_word.ppp_type
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    private String pppType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp_word.ppp_model
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    private String pppModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp_word.ppp_assets
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    private Double pppAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp_word.ppp_level
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    private String pppLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp_word.ppp_utime
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    private Date pppUtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp_word.ppp_itime
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    private Date pppItime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp_word.ppp_id
     *
     * @return the value of bhi_ppp_word.ppp_id
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public Integer getPppId() {
        return pppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp_word.ppp_id
     *
     * @param pppId the value for bhi_ppp_word.ppp_id
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void setPppId(Integer pppId) {
        this.pppId = pppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp_word.ppp_name
     *
     * @return the value of bhi_ppp_word.ppp_name
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public String getPppName() {
        return pppName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp_word.ppp_name
     *
     * @param pppName the value for bhi_ppp_word.ppp_name
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void setPppName(String pppName) {
        this.pppName = pppName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp_word.ppp_region
     *
     * @return the value of bhi_ppp_word.ppp_region
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public String getPppRegion() {
        return pppRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp_word.ppp_region
     *
     * @param pppRegion the value for bhi_ppp_word.ppp_region
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void setPppRegion(String pppRegion) {
        this.pppRegion = pppRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp_word.ppp_area
     *
     * @return the value of bhi_ppp_word.ppp_area
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public String getPppArea() {
        return pppArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp_word.ppp_area
     *
     * @param pppArea the value for bhi_ppp_word.ppp_area
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void setPppArea(String pppArea) {
        this.pppArea = pppArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp_word.ppp_ind
     *
     * @return the value of bhi_ppp_word.ppp_ind
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public String getPppInd() {
        return pppInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp_word.ppp_ind
     *
     * @param pppInd the value for bhi_ppp_word.ppp_ind
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void setPppInd(String pppInd) {
        this.pppInd = pppInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp_word.ppp_type
     *
     * @return the value of bhi_ppp_word.ppp_type
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public String getPppType() {
        return pppType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp_word.ppp_type
     *
     * @param pppType the value for bhi_ppp_word.ppp_type
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void setPppType(String pppType) {
        this.pppType = pppType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp_word.ppp_model
     *
     * @return the value of bhi_ppp_word.ppp_model
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public String getPppModel() {
        return pppModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp_word.ppp_model
     *
     * @param pppModel the value for bhi_ppp_word.ppp_model
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void setPppModel(String pppModel) {
        this.pppModel = pppModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp_word.ppp_assets
     *
     * @return the value of bhi_ppp_word.ppp_assets
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public Double getPppAssets() {
        return pppAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp_word.ppp_assets
     *
     * @param pppAssets the value for bhi_ppp_word.ppp_assets
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void setPppAssets(Double pppAssets) {
        this.pppAssets = pppAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp_word.ppp_level
     *
     * @return the value of bhi_ppp_word.ppp_level
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public String getPppLevel() {
        return pppLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp_word.ppp_level
     *
     * @param pppLevel the value for bhi_ppp_word.ppp_level
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void setPppLevel(String pppLevel) {
        this.pppLevel = pppLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp_word.ppp_utime
     *
     * @return the value of bhi_ppp_word.ppp_utime
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public Date getPppUtime() {
        return pppUtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp_word.ppp_utime
     *
     * @param pppUtime the value for bhi_ppp_word.ppp_utime
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void setPppUtime(Date pppUtime) {
        this.pppUtime = pppUtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp_word.ppp_itime
     *
     * @return the value of bhi_ppp_word.ppp_itime
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public Date getPppItime() {
        return pppItime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp_word.ppp_itime
     *
     * @param pppItime the value for bhi_ppp_word.ppp_itime
     *
     * @mbggenerated Tue Feb 07 16:31:00 GMT+08:00 2017
     */
    public void setPppItime(Date pppItime) {
        this.pppItime = pppItime;
    }
}