package com.unbank.mybatis.vo;

public class BhiPPPWithBLOBs extends BhiPPP {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp.info
     *
     * @mbggenerated Tue Jul 19 16:37:13 GMT+08:00 2016
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bhi_ppp.description
     *
     * @mbggenerated Tue Jul 19 16:37:13 GMT+08:00 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp.info
     *
     * @return the value of bhi_ppp.info
     *
     * @mbggenerated Tue Jul 19 16:37:13 GMT+08:00 2016
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp.info
     *
     * @param info the value for bhi_ppp.info
     *
     * @mbggenerated Tue Jul 19 16:37:13 GMT+08:00 2016
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bhi_ppp.description
     *
     * @return the value of bhi_ppp.description
     *
     * @mbggenerated Tue Jul 19 16:37:13 GMT+08:00 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bhi_ppp.description
     *
     * @param description the value for bhi_ppp.description
     *
     * @mbggenerated Tue Jul 19 16:37:13 GMT+08:00 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}