package com.unbank.mybatis.vo;

public class BhiPPP {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_ppp.id
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bhi_ppp.provice
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	private String provice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_ppp.id
	 * @return  the value of bhi_ppp.id
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_ppp.id
	 * @param id  the value for bhi_ppp.id
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bhi_ppp.provice
	 * @return  the value of bhi_ppp.provice
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	public String getProvice() {
		return provice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bhi_ppp.provice
	 * @param provice  the value for bhi_ppp.provice
	 * @mbggenerated  Tue Jul 19 16:37:13 GMT+08:00 2016
	 */
	public void setProvice(String provice) {
		this.provice = provice;
	}
}